% @result results: a ModelResults
% @param inputs: a AppInputs
function [daily, cumulative] = runModel(input)
  [t, y] = COVID5C_Run_App( input.icATExpHR * 0.01, ...
	       input.icATRecHR * 0.01, ...
	       input.icATExpLR * 0.01, ...
	       input.icATRecLR * 0.01, ...
	       input.icStaffExpHR * 0.01, ...
	       input.icStaffRecHR * 0.01, ...
	       input.icStaffExpLR * 0.01, ...
	       input.icStaffRecLR * 0.01, ...
	       input.icSExpC * 0.01, ...
	       input.icSRecC * 0.01, ...
	       input.icSExpNC * 0.01, ...
	       input.icSRecNC * 0.01, ...
	       input.soATHR * 0.01, ...
	       input.soATLR * 0.01, ...
	       input.soStaffHR, ...
	       input.soStaffLR, ...
	       input.soSC, ...
	       input.soSNC, ...
	       input.propNC * 0.01, ...
	       input.scaleTracking * 0.01, ...
	       input.incAsymp * 0.01, ...
           input.betaScaling * 0.01);
  daily = DailyResults(t, y);
  cumulative = CumulativeResults(t, y);
end
