% @result results: a ModelResults
% @param inputs: a AppInputs
function results = runModel(input)
  [t, y] = COVID5C_Run_App( input.icAdminTeachExpHR, ...
	       input.icAdminTeachRecHR, ...
	       input.icAdminTeachExpLR, ...
	       input.icAdminTeachRecLR, ...
	       input.icStaffExpHR, ...
	       input.icStaffRecHR, ...
	       input.icStaffExpLR, ...
	       input.icStaffRecLR, ...
	       input.icSExpC, ...
	       input.icSRecC, ...
	       input.icSExpNC, ...
	       input.icSRecNC, ...
	       input.soAdminTeachHR, ...
	       input.soAdminTeachLR, ...
	       input.soStaffHR, ...
	       input.soStaffLR, ...
	       input.soSC, ...
	       input.soSNC, ...
	       input.propNC, ...
	       input.scaleTracking, ...
	       input.incAsymp);
  results = ModelResults(t, y);
end
