% @result results: a ModelResults
% @param inputs: a AppInputs
function results = runModel(input)
  [t, y] = COVID5C_Run_App( input.icAdminTeachExpHR * 0.01, ...
	       input.icAdminTeachRecHR * 0.01, ...
	       input.icAdminTeachExpLR * 0.01, ...
	       input.icAdminTeachRecLR * 0.01, ...
	       input.icStaffExpHR * 0.01, ...
	       input.icStaffRecHR * 0.01, ...
	       input.icStaffExpLR * 0.01, ...
	       input.icStaffRecLR * 0.01, ...
	       input.icSExpC * 0.01, ...
	       input.icSRecC * 0.01, ...
	       input.icSExpNC * 0.01, ...
	       input.icSRecNC * 0.01, ...
	       input.soAdminTeachHR * 0.01, ...
	       input.soAdminTeachLR * 0.01, ...
	       input.soStaffHR, ...
	       input.soStaffLR, ...
	       input.soSC, ...
	       input.soSNC, ...
	       input.propNC * 0.01, ...
	       input.scaleTracking * 0.01, ...
	       input.incAsymp * 0.01);
  results = ModelResults(t, y);
end
